### ISSUE TITLE
Avatar Initials gets a misplaced UI

### ISSUE THREAD

**Issue by kushagra21** [avishayil/react-native-user-avatar#11]
**Issue:** 

Avatar Initials UI gets misplaced when the "name" property is provided with a string which a has multiple capital alphabets.

**Step to Reproduce :** 

`<UserAvatar size="100" name="AVISHAY" src="" />`

or,

`<UserAvatar size="100" name="AVISHAY BAR" src="" />`

**Comment by avishayil** [comment]
Couldn't replicate it, seems it works fine now.
