### ISSUE TITLE
Not Dynamic

### ISSUE THREAD

**Issue by SirPhemmiey** [avishayil/react-native-user-avatar#12]
if i do something like this
`<UserAvatar name="John Doe" size={100} color="#6c5ce7"  />` it works fine.

But if i do something like 
`<UserAvatar name={this.state.provider_name} size={100} color="#6c5ce7"  />` it says  the Avatart requires a name.

Please what do i need to do?
Thanks

**Comment by alvinmatias69** [comment]
I think it's caused because ```this.state.provider_name``` doesn't has a value before. Therefore ```undefined``` is passed to the name props. Could you elaborate with your code?

**Comment by michaelxtendly** [comment]
I have the same Issue for this :(

**Comment by avishayil** [comment]
Seems like it's not the library issue
