### ISSUE TITLE
Fallback not working

### ISSUE THREAD

**Issue by rkostrab** [avishayil/react-native-user-avatar#16]
When I render proper image:
```
<UserAvatar size="100" name="Avishay Bar" src={"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/1200px-Cat03ds.jpg"}/>
```
... it is working fine.
But if I make an error in URL which results in 404 then avatar is blank (no letters)
```
<UserAvatar size="100" name="Avishay Bar" src={"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat0"}/>
```

**Comment by SanchezQb** [comment]
Did you ever find a fix for this?

**Comment by avishayil** [comment]
I'll check this.

**Comment by abdulhamidOumer** [comment]
@avishayil is this fixed now ?

**Comment by avishayil** [comment]
Since dynamic require is not supported by metro, you should handle this on your application logic. Trying to require the image in your code and if it succeeds than render the component.
