### ISSUE TITLE
Suggestion: allow to set border color (optional props)

### ISSUE THREAD

**Issue by fuj1w4r4** [avishayil/react-native-user-avatar#18]
Hi,

I am suggesting to allow to set border color (optional props). Please advise.

**Comment by fuj1w4r4** [comment]
any update?

**Comment by infaz** [comment]
<UserAvatar style={[{
                                    backgroundColor: #FFFFFF, borderColor: #000000,
                                    borderWidth: 3 }]} size="100" name="Avishay Bar" />
