### ISSUE TITLE
How to use with react-native-fast-image?

### ISSUE THREAD

**Issue by rdgomt** [avishayil/react-native-user-avatar#33]
Hi!

I'm wondering if there is a way to use UserAvatar with FastImage as a custom component. I've tried with `component={<FastImage source={{ uri: ... }}}/>` but did not work.

https://github.com/DylanVann/react-native-fast-image/

**Comment by avishayil** [comment]
Should be fine with #40

**Comment by leoz** [comment]
It stopped working in v1.0.6.

**Comment by avishayil** [comment]
@leoz can you attach screenshots / logs?

**Comment by avishayil** [comment]
This is now documented on the readme.
