### ISSUE TITLE
Custom components got broken in v1.0.6

### ISSUE THREAD

**Issue by leoz** [avishayil/react-native-user-avatar#41]
Custom component support got broken in v1.0.6. It works fine in v1.0.5. Try to supply `component={Image}` to verify.

**Comment by avishayil** [comment]
I added some tests in the latest commit, please see if you can run the example

**Comment by avishayil** [comment]
I tried it with 1.0.6 and seems that if you want to render an image you have to specify in the image tag the height and width, but I think that's not related to this library but how React Native image component works.

**Comment by leoz** [comment]
Here you are: https://github.com/leoz/bug-in-user-avatar
See my comments inline in the code.

**Comment by avishayil** [comment]
I understand. I think that the way it rendered a custom component had changed. Until 1.0.5 it was supporting only image components. But now it handles every component as a children, so if you'd like to use the image component you can take a look on the example on the master branch. I'll make a pull request to your example to demonstrate how it works in 1.0.6

**Comment by leoz** [comment]
@avishayil , sure thing. Thanks!

Maybe it would makes sense to include it into the docs and example for the `react-native-user-avatar` repo itself.

Also another small thing: the example code in readme is incorrect. `size="100"` throws a warning. The size shall be a number and to be defined like this `size={100}`.

**Comment by avishayil** [comment]
Thanks for the feedback. I'll change the references in the readme.
