### ISSUE TITLE
Extend useEffect to render the image in case it changes

### ISSUE THREAD

**Issue by ciprian-iacob** [avishayil/react-native-user-avatar#49]
Hi,

Great improvements on the package, thanks for taking the time to share it with us.

I have a suggestion though in src/index.js [line 50](https://github.com/avishayil/react-native-user-avatar/blob/97410a3d08992ffd952226270790dedae68434b7/src/index.js#L50) to extend the `useEffect` for changes to `src` prop. E.g `useEffect(() =>  // magic here),[src]);`;

I'm not quite sure if my assumption is right but I have a case of an image upload that fails to re-render because this effect works only when component is mounted.

Should you have further questions, please let me know.

Ciprian

**Comment by avishayil** [comment]
Hi @ciprian-iacob , can you open a pull request with this change?
Great suggestion.

**Comment by sylvainemery** [comment]
Hi @avishayil, we use your package and are very happy with it, thanks for your work.
There is this bug that can be closed by #72 , would you have the time to review and merge it?
Thanks,

**Comment by avishayil** [comment]
Should be fixed with [v1.0.8](https://github.com/avishayil/react-native-user-avatar/releases/tag/v1.0.8)
