### ISSUE TITLE
Abort downloading when unmount is triggered

### ISSUE THREAD

**Issue by Jerome91410** [avishayil/react-native-user-avatar#50]
When you have bad network and/or the image to display is too hughe, it could be nice to abort fetch downloading when you unmount the component.

It will fix an error found on my project:

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

<img width="1902" alt="Capture d’écran 2020-05-18 à 15 30 28" src="https://user-images.githubusercontent.com/44202034/82218670-8b189700-991c-11ea-97af-c2c9bcecf717.png">

**Comment by avishayil** [comment]
Thanks @Jerome91410

**Comment by avishayil** [comment]
fixed with #51
