### ISSUE TITLE
textStyle prop is not showing any effect

### ISSUE THREAD

**Issue by Yandamuri** [avishayil/react-native-user-avatar#62]
Blow is my my code for avatar

       <UserAvatar style={avatarStyle} name={displayname} textStyle={avatarTextStyle} textColor={'black'} />

And `textStyle` is as shown below

      avatarTextStyle: {
          fontFamily: 'OpenSans-Bold',
          fontSize: 24,
          lineHeight: 33,
          color: '#1A7AF3',
      }

But this style is not showing any effect at all. no change in fontSize, font color.

**Version:** "react-native-user-avatar": "^1.0.7",

**Comment by derick-bai** [comment]
Looks like the code is there 437e8aa8b95bbd24ff1fb733c231b0f69a257e43. So it seems that the `textStyle` prop was introduced back to Sep and the documentation was updated, but a release was not made afterwards. So the 1.0.7 version that we got via npm actually does not have support for `textStyle`.

Maybe just making a new release would solve this issue? @avishayil

**Comment by Yandamuri** [comment]
@derick-bai have any idea about when would we get that textStyle update?

**Comment by avishayil** [comment]
I'll publish a new release this weekend

**Comment by Yandamuri** [comment]
@avishayil Thank you so much for your update. Is there any way that we can come to know as soon as update is release?

**Comment by Higr25** [comment]
@avishayil textStyle prop still doesn't seem to have any effect, any update on this?

**Comment by jlpujante** [comment]
> @avishayil textStyle prop still doesn't seem to have any effect, any update on this?

I had the same problem, so I've created a patch to fix it. Please use it:

diff --git a/node_modules/react-native-user-avatar/src/components/TextAvatar.js b/node_modules/react-native-user-avatar/src/components/TextAvatar.js
old mode 100644
new mode 100755
index a2c4a49..24236e7
--- a/node_modules/react-native-user-avatar/src/components/TextAvatar.js
+++ b/node_modules/react-native-user-avatar/src/components/TextAvatar.js
@@ -8,6 +8,7 @@ const TextAvatar = (props) => {
     name,
     size,
     textColor,
+    textStyle
   } = props;

   const textContainerStyle = {
@@ -22,10 +23,10 @@ const TextAvatar = (props) => {
   return (
     <View style={textContainerStyle}>
       <Text
-        style={{
+        style={[textStyle, {
           color: textColor,
           fontSize: size / 2.5,
-        }}
+        }]}
         adjustsFontSizeToFit={true}
       >
         {abbr(name)}
diff --git a/node_modules/react-native-user-avatar/src/helpers.js b/node_modules/react-native-user-avatar/src/helpers.js
old mode 100644
new mode 100755
index 2297fd2..1275950
--- a/node_modules/react-native-user-avatar/src/helpers.js
+++ b/node_modules/react-native-user-avatar/src/helpers.js
@@ -9,6 +9,9 @@ export const abbr = (name) => {
     console.warn('Could not get abbr from name');
     abbr = name;
   }
+  if (abbr.length > 3) {
+    abbr = abbr.substr(0,3);
+  }
   return abbr;
 };

diff --git a/node_modules/react-native-user-avatar/src/index.js b/node_modules/react-native-user-avatar/src/index.js
old mode 100644
new mode 100755
index 2ac1719..73a5521
--- a/node_modules/react-native-user-avatar/src/index.js
+++ b/node_modules/react-native-user-avatar/src/index.js
@@ -12,6 +12,10 @@ import {
   generateBackgroundStyle,
 } from './helpers';

+const AVATAR_TEXT_TYPE = 'text';
+const AVATAR_CUSTOM_TYPE = 'custom';
+const AVATAR_IMAGE_TYPE = 'image';
+
 const UserAvatar = (props) => {
   let {
     name,
@@ -19,6 +23,7 @@ const UserAvatar = (props) => {
     bgColor,
     bgColors,
     textColor,
+    textStyle,
     size,
     imageStyle,
     style,
@@ -32,15 +37,20 @@ const UserAvatar = (props) => {
     size = parseInt(size);
   }

+  const innerType = AVATAR_TEXT_TYPE;
   const [inner, setInner] = useState(
-      <TextAvatar textColor={textColor} size={size} name={name} />,
+      <TextAvatar textColor={textColor} textStyle={textStyle} size={size} name={name} />,
   );

   useEffect(() => {
-    if (component) setInner(<CustomAvatar size={size} component={component} />);
+    if (component) {
+      innerType = AVATAR_CUSTOM_TYPE;
+      setInner(<CustomAvatar size={size} component={component}/>);
+    }
     if (src) {
       fetchImage(src).then((isImage) => {
         if (isImage) {
+          innerType = AVATAR_IMAGE_TYPE;
           setInner(
               <ImageAvatar src={src} size={size} imageStyle={imageStyle} />,
           );
@@ -55,7 +65,12 @@ const UserAvatar = (props) => {
       getContainerStyle(size, src, borderRadius),
       style]}
     >
-      {inner}
+      {
+        innerType === AVATAR_TEXT_TYPE ?
+          <TextAvatar textColor={textColor} textStyle={textStyle} size={size} name={name} />
+          :
+          {inner}
+      }
     </View>
   );
 };

**Comment by jlpujante** [comment]
> I had the same problem, so I've created a patch to fix it. Please use it:

Please use this patch to fix it:
https://github.com/avishayil/react-native-user-avatar/issues/62#issuecomment-983841764

**Comment by jlpujante** [comment]
> @avishayil Thank you so much for your update. Is there any way that we can come to know as soon as update is release?

https://github.com/avishayil/react-native-user-avatar/issues/62#issuecomment-983841764

**Comment by avishayil** [comment]
Should be fixed with [v1.0.8](https://github.com/avishayil/react-native-user-avatar/releases/tag/v1.0.8)
