### ISSUE TITLE
Could not get abbr from name

### ISSUE THREAD

**Issue by joeyfigaro** [avishayil/react-native-user-avatar#64]
Looks like another user was having the same issue, but they closed the ticket—#56 

Initials are rendering just fine, but this warning gets spammed intermittently. 

https://github.com/avishayil/react-native-user-avatar/blob/b42b26ad24e7c7730a0ea49d6d30141625194376/src/helpers.js#L8-L11

Since default props are set, you could always fallback to 'JD'—it looks like the root issue is somewhere in the `initials` package.

**Comment by avishayil** [comment]
Should be fixed with [v1.0.8](https://github.com/avishayil/react-native-user-avatar/releases/tag/v1.0.8)
