### ISSUE TITLE
Cannot resolve module 'react-native' when using on web.

### ISSUE THREAD

**Issue by sankomil** [avishayil/react-native-user-avatar#70]
Hi, I'm trying to use the library on a web server which is running using NextJS. When I try to use the UserAvatar component, I receive the following error:

![image](https://user-images.githubusercontent.com/43489998/103509758-d200d000-4e9e-11eb-9e1d-fb37825729b7.png)

**Comment by walidvb** [comment]
I would assume you need to set up NextJS to include `react-native` and `react-native-web`, as well as configure the webpack alias.
