### ISSUE TITLE
[web] Images with specific CORS headers give false negative

### ISSUE THREAD

**Issue by walidvb** [avishayil/react-native-user-avatar#89]
I'm loading images from gravatar, and it seems that using the `fetch` API returns an error, even though the image would be correctly loaded by the browser.

I'll try and make a PR to address this, by changing the behaviour on web, along the lines of:

```
 const image = document.createElement('img');

  image.onload = setImageWorked;
  image.onerror = doUseFallback;
  image.referrerPolicy = 'no-referrer';
  image.src = src;
```

**Comment by avishayil** [comment]
Should be fixed with [v1.0.8](https://github.com/avishayil/react-native-user-avatar/releases/tag/v1.0.8)
