### ISSUE TITLE
component property is not working properly

### ISSUE THREAD

**Issue by zhaonian** [avishayil/react-native-user-avatar#9]
```
import { CachedImage } from 'react-native-cached-image';

const avatarImage = (
        <CachedImage
                source={{
                        uri: this.props.userAvatar
                                ? `${avatarUrl}/${this.props.userAvatar}/downloadMedia`
                                : null
                }}
        />
);

<UserAvatar
        size="50"
        name={this.props.fullname}
        color={'#9B9B9B'}
        style={[styles.avatar, { padding: 2 }]}
        component={avatarImage}
/>
```

The `component` property is not working. not showing anything. I also tried with built-in `<Image />`, still no luck.

**Comment by SirPhemmiey** [comment]
Any fix to this?

**Comment by jpovmarques** [comment]
I got the same problem

**Comment by yamgemy** [comment]
if you had a look at the source, the props src must be set before either built-in Image or CachedImage would be rendered. The component prop expects simply the class imported.

`import { CachedImage } from 'react-native-cached-image';`
`
<UserAvatar
        size="50"
        src={https://www.asdfasdf.com/imagelocaation.jpg}
        component={CachedImage }
/>
`

works for me
