### ISSUE TITLE
Is it possible to restrict the number of characters in the Avatar?

### ISSUE THREAD

**Issue by Yandamuri** [avishayil/react-native-user-avatar#91]
This is how Avatar looks like if given name has more than three words

![WhatsApp Image 2021-10-27 at 4 27 21 PM](https://user-images.githubusercontent.com/31983789/139053292-255c5382-3f42-4a57-86dd-e5d04a5d3527.jpeg)

I want to restrict the Avatar to first three words of the given name. 

Is that possible?

**Comment by jlpujante** [comment]
> This is how Avatar looks like if given name has more than three words
> 
> ![WhatsApp Image 2021-10-27 at 4 27 21 PM](https://user-images.githubusercontent.com/31983789/139053292-255c5382-3f42-4a57-86dd-e5d04a5d3527.jpeg)
> 
> I want to restrict the Avatar to first three words of the given name.
> 
> Is that possible?

I had the same problem, so I've created a patch to fix it and set a maximum of 3 characters. Please use it:
[react-native-user-avatar+1.0.7.txt](https://github.com/avishayil/react-native-user-avatar/files/7635824/react-native-user-avatar%2B1.0.7.txt)

**Comment by Yandamuri** [comment]
@jlpujante Thank you

**Comment by avishayil** [comment]
Hi @jlpujante can you make a PR with this change?

**Comment by avishayil** [comment]
#95 merged and will be released this week.
